package tui

// cweNames donne un nom court en français aux CWE les plus fréquentes dans
// les sources (référence : https://cwe.mitre.org).
var cweNames = map[string]string{
	"CWE-20":   "validation d'entrée incorrecte",
	"CWE-22":   "path traversal, accès hors du dossier prévu",
	"CWE-23":   "path traversal relatif",
	"CWE-59":   "suivi de lien symbolique",
	"CWE-61":   "suivi de lien symbolique UNIX",
	"CWE-73":   "chemin de fichier contrôlé de l'extérieur",
	"CWE-74":   "injection",
	"CWE-77":   "injection de commande",
	"CWE-78":   "injection de commande système",
	"CWE-79":   "XSS, injection de script dans la page",
	"CWE-80":   "XSS basique",
	"CWE-88":   "injection d'arguments",
	"CWE-89":   "injection SQL",
	"CWE-91":   "injection XML / XPath",
	"CWE-93":   "injection CRLF",
	"CWE-94":   "injection de code",
	"CWE-95":   "injection via eval",
	"CWE-113":  "HTTP response splitting (CRLF)",
	"CWE-116":  "encodage ou échappement de sortie incorrect",
	"CWE-117":  "injection dans les journaux",
	"CWE-119":  "accès mémoire hors limites",
	"CWE-120":  "buffer overflow classique",
	"CWE-121":  "débordement de pile (stack overflow)",
	"CWE-122":  "débordement de tas (heap overflow)",
	"CWE-125":  "lecture hors limites",
	"CWE-129":  "index de tableau non validé",
	"CWE-134":  "chaîne de format non contrôlée",
	"CWE-178":  "casse mal gérée",
	"CWE-184":  "liste d'entrées interdites incomplète",
	"CWE-190":  "dépassement d'entier",
	"CWE-191":  "soupassement d'entier",
	"CWE-200":  "exposition d'informations sensibles",
	"CWE-201":  "données sensibles dans une réponse",
	"CWE-203":  "écart observable (canal auxiliaire)",
	"CWE-204":  "réponses différentes selon le cas (énumération)",
	"CWE-208":  "écart de temps de réponse (timing)",
	"CWE-209":  "message d'erreur trop bavard",
	"CWE-248":  "exception non interceptée",
	"CWE-250":  "exécution avec des privilèges inutiles",
	"CWE-252":  "valeur de retour non vérifiée",
	"CWE-256":  "mot de passe stocké en clair",
	"CWE-266":  "privilèges attribués à tort",
	"CWE-269":  "gestion des privilèges incorrecte",
	"CWE-276":  "permissions par défaut incorrectes",
	"CWE-280":  "permissions insuffisantes mal gérées",
	"CWE-281":  "permissions non préservées",
	"CWE-284":  "contrôle d'accès incorrect",
	"CWE-285":  "autorisation incorrecte",
	"CWE-287":  "authentification incorrecte",
	"CWE-288":  "contournement d'authentification par un autre chemin",
	"CWE-290":  "contournement d'authentification par usurpation",
	"CWE-294":  "rejeu de données capturées",
	"CWE-295":  "certificat mal validé",
	"CWE-306":  "authentification absente sur une fonction critique",
	"CWE-307":  "tentatives d'authentification illimitées",
	"CWE-311":  "données sensibles non chiffrées",
	"CWE-312":  "données sensibles stockées en clair",
	"CWE-319":  "données sensibles transmises en clair",
	"CWE-326":  "chiffrement trop faible",
	"CWE-327":  "algorithme cryptographique cassé ou risqué",
	"CWE-330":  "aléa insuffisant",
	"CWE-331":  "entropie insuffisante",
	"CWE-345":  "authenticité des données mal vérifiée",
	"CWE-346":  "origine mal vérifiée",
	"CWE-347":  "signature cryptographique mal vérifiée",
	"CWE-352":  "CSRF, requête forgée à l'insu de l'utilisateur",
	"CWE-354":  "somme de contrôle mal validée",
	"CWE-359":  "exposition de données personnelles",
	"CWE-362":  "condition de course",
	"CWE-367":  "TOCTOU (vérification puis usage décalés)",
	"CWE-369":  "division par zéro",
	"CWE-377":  "fichier temporaire non sûr",
	"CWE-384":  "fixation de session",
	"CWE-400":  "consommation de ressources non maîtrisée (DoS)",
	"CWE-401":  "fuite mémoire",
	"CWE-404":  "ressource mal libérée",
	"CWE-407":  "complexité algorithmique exploitable",
	"CWE-409":  "données très compressées (bombe de décompression)",
	"CWE-415":  "double libération (double free)",
	"CWE-416":  "utilisation après libération (use after free)",
	"CWE-434":  "téléversement de fichier dangereux",
	"CWE-436":  "interprétations divergentes",
	"CWE-441":  "intermédiaire détourné (confused deputy)",
	"CWE-444":  "HTTP request smuggling",
	"CWE-470":  "réflexion non sûre",
	"CWE-476":  "déréférencement de pointeur NULL",
	"CWE-494":  "code téléchargé sans contrôle d'intégrité",
	"CWE-502":  "désérialisation de données non fiables",
	"CWE-521":  "exigences de mot de passe faibles",
	"CWE-522":  "identifiants mal protégés",
	"CWE-532":  "données sensibles dans les journaux",
	"CWE-552":  "fichiers accessibles à des tiers",
	"CWE-601":  "redirection ouverte",
	"CWE-610":  "ressource désignée de l'extérieur",
	"CWE-611":  "XXE, entités externes XML",
	"CWE-613":  "expiration de session insuffisante",
	"CWE-617":  "assertion atteignable (plantage)",
	"CWE-639":  "IDOR, accès via un identifiant modifiable",
	"CWE-640":  "récupération de mot de passe faible",
	"CWE-665":  "initialisation incorrecte",
	"CWE-668":  "ressource exposée au mauvais périmètre",
	"CWE-670":  "flux de contrôle toujours incorrect",
	"CWE-674":  "récursion non contrôlée",
	"CWE-681":  "conversion numérique incorrecte",
	"CWE-682":  "calcul incorrect",
	"CWE-693":  "mécanisme de protection défaillant",
	"CWE-697":  "comparaison incorrecte",
	"CWE-703":  "cas exceptionnels mal gérés",
	"CWE-704":  "conversion de type incorrecte",
	"CWE-732":  "permissions incorrectes sur une ressource critique",
	"CWE-754":  "conditions inhabituelles mal vérifiées",
	"CWE-755":  "exceptions mal gérées",
	"CWE-770":  "allocation de ressources sans limite",
	"CWE-772":  "ressource jamais libérée",
	"CWE-776":  "expansion d'entités XML (billion laughs)",
	"CWE-787":  "écriture hors limites",
	"CWE-789":  "allocation mémoire démesurée",
	"CWE-798":  "identifiants codés en dur",
	"CWE-807":  "décision de sécurité sur une entrée non fiable",
	"CWE-824":  "pointeur non initialisé",
	"CWE-829":  "inclusion de code d'une source non fiable",
	"CWE-834":  "itérations excessives",
	"CWE-835":  "boucle infinie",
	"CWE-843":  "confusion de type",
	"CWE-862":  "autorisation manquante",
	"CWE-863":  "autorisation incorrecte",
	"CWE-908":  "ressource non initialisée",
	"CWE-909":  "initialisation manquante",
	"CWE-915":  "attributs d'objet modifiables (mass assignment)",
	"CWE-916":  "hachage de mot de passe trop faible",
	"CWE-917":  "injection de langage d'expression",
	"CWE-918":  "SSRF, requêtes forcées depuis le serveur",
	"CWE-1021": "clickjacking",
	"CWE-1188": "valeur par défaut non sûre",
	"CWE-1236": "injection de formule CSV",
	"CWE-1284": "quantité en entrée non validée",
	"CWE-1321": "pollution de prototype",
	"CWE-1333": "ReDoS, expression régulière coûteuse",
	"CWE-1336": "injection de template (SSTI)",
	"CWE-1395": "dépendance tierce vulnérable",
}

// helpLines est l'écran d'aide (touche ?) : touches, légende, glossaire.
// C'est une fonction car les couleurs dépendent du thème du terminal.
func helpLines() []string {
	return []string{
		bold + "Touches" + reset,
		"  taper            filtrer les résultats (CVE, produit, CWE, mot-clé…)",
		"  ↑ / ↓            naviguer dans la liste, ou faire défiler le détail",
		"  PgUp / PgDn      page précédente / suivante",
		"  Début / Fin      premier / dernier résultat",
		"  Ctrl-G           aller directement au résultat n° … (ex. 23456, puis Entrée)",
		"  Tab              passer de la liste au détail et inversement",
		"  Ctrl-← / Ctrl-→  élargir / rétrécir le panneau liste (ou glisser la séparation à la souris)",
		"  molette          faire défiler la liste ou le détail selon le panneau survolé",
		"  Entrée           ouvrir la fiche en plein écran (Entrée ou Esc pour revenir)",
		"  ?                afficher / fermer cette aide",
		"  Esc / Ctrl-C     quitter (Esc ferme d'abord l'aide)",
		"",
		bold + "Recherche" + reset,
		"  Chaque mot est un début de mot (deserializ → deserialization) ; plusieurs mots se cumulent.",
		"  Casse et accents ignorés. Champs cherchés : identifiants et alias, titre, résumé, composant,",
		"  type, versions affectées et corrigées, remédiation.",
		"",
		bold + "Filtres" + reset + "  (combinables entre eux et avec du texte : nginx sev:high+ src:osv)",
		"  sev:crit         sévérité : crit, high, med, low, inconnue (ou critique, elevee, moyenne, faible)",
		"  sev:crit,high    plusieurs sévérités",
		"  sev:high+        cette sévérité ou plus grave",
		"  src:kev          source : kev, osv, fr, nvd, ia ; plusieurs possibles (src:kev,fr)",
		"                   Un CVE déjà décrit par OSV, KEV ou un article n'apparaît pas en double",
		"                   côté NVD ; src:nvd affiche tout de même toutes les entrées NVD.",
		"  exploitee        failles exploitées activement (CVE présent dans CISA KEV), toutes sources",
		"  exploit          un exploit ou une preuve de concept public existe (Exploit-DB, Metasploit, GitHub)",
		"  mes              seulement les produits surveillés (liste : vulnkb watch add nginx vtiger…)",
		"  Sévérité : celle de la source, sinon la plus haute sévérité NVD des CVE de l'entrée.",
		"",
		bold + "Légende de la liste" + reset,
		"  " + boldRed + "●" + reset + "                faille exploitée activement (présente dans le catalogue CISA KEV)",
		"  " + red + "CRIT" + reset + " " + orange + "HIGH" + reset + " " + yellow + "MED" + reset + " " + gray + "LOW" + reset + "  sévérité : critique, élevée, moyenne, faible ( · = inconnue)",
		"  " + boldRed + "KEV" + reset + "              catalogue CISA des failles exploitées",
		"  " + green + "OSV" + reset + "              base OSV.dev des paquets open source",
		"  " + blue + "FR" + reset + "               avis ou alerte du CERT-FR, en français",
		"  " + cyan + "NVD" + reset + "              base CVE du NIST : tous les CVE, y compris hors paquets (ex. vtiger)",
		"  " + magenta + "IA" + reset + "               article dont la fiche a été extraite par un LLM : à relire",
		"",
		bold + "Identifiants" + reset,
		"  CVE-AAAA-NNNN    identifiant universel d'une faille, attribué par le programme CVE (MITRE)",
		"  GHSA-xxxx-…      avis de la GitHub Advisory Database ; souvent doublé d'un CVE",
		"  GO-, PYSEC-,     avis des bases propres à Go, Python (PyPI) et Rust ; les alias",
		"  RUSTSEC-         d'une même faille sont listés entre parenthèses",
		"  CERTFR-…-AVI     avis du CERT-FR ; CERTFR-…-ALE pour une alerte (menace active)",
		"",
		bold + "Notions" + reset,
		"  CWE              catégorie de faiblesse (CWE-79 = XSS) ; son nom s'affiche dans le détail",
		"  CVSS             score de gravité de 0 à 10, calculé à partir d'un vecteur :",
		"                   AV vecteur d'attaque (N réseau, L local), AC complexité, PR privilèges requis,",
		"                   UI interaction utilisateur, S portée, C/I/A impact confidentialité/intégrité/disponibilité",
		"  KEV              Known Exploited Vulnerabilities : failles vues exploitées, à corriger en priorité",
		"  OSV              Open Source Vulnerabilities (osv.dev), agrège GitHub, PyPI, Go, RustSec…",
		"  CERT-FR          centre de veille et d'alerte de l'ANSSI",
		"  Remédiation      action qui supprime le risque (mise à jour, configuration, contournement)",
		"  Backport         correctif reporté sur une ancienne version, ex. dans un paquet Debian",
		"  PoC              preuve de concept : code qui démontre la faille",
		"  0-day            faille exploitée avant qu'un correctif existe",
		"",
		bold + "Types de failles courants" + reset,
		"  RCE              exécution de code à distance",
		"  LPE              élévation de privilèges locale",
		"  XSS              script injecté dans une page vue par d'autres utilisateurs",
		"  CSRF             action déclenchée à l'insu d'un utilisateur connecté",
		"  SSRF             le serveur est amené à envoyer des requêtes choisies par l'attaquant",
		"  SQLi             injection SQL : requête modifiée via une entrée",
		"  XXE              lecture de fichiers ou SSRF via des entités XML externes",
		"  Path traversal   accès à des fichiers hors du dossier prévu (../)",
		"  IDOR             accès aux données d'un autre en changeant un identifiant",
		"  Désérialisation  objets reconstruits depuis des données non fiables, souvent vers une RCE",
		"  DoS              déni de service : rendre le service indisponible",
		"  Heap / stack     débordement de tampon en mémoire (tas / pile)",
		"  overflow",
		"  UAF / OOB        use after free / accès hors limites : corruptions mémoire",
	}
}
